// ─── SHARED COMPONENTS ───────────────────────────────────────────────────────
const Card = ({ children, style={} }) =>
  h('div', { style:{ background:white, border:"1px solid "+cardBd, borderRadius:12,
    boxShadow:"0 2px 12px rgba(27,43,94,0.07)", ...style }}, children);

const PageWrap = ({ children }) =>
  h('div', { style:{ maxWidth:820, margin:"0 auto", padding:"40px 24px 80px" }}, children);

const PrimaryBtn = ({ children, onClick, disabled, style:extra={} }) =>
  h('button', { onClick, disabled,
    style:{ background: disabled?"#B0BAD0":navy, color:white, border:"none",
      borderRadius:10, padding:"15px 32px", fontSize:15, fontWeight:600,
      cursor: disabled?"not-allowed":"pointer", display:"block", width:"100%",
      fontFamily:ffs, transition:"background 0.2s", ...extra }},
    children);

const scrollTop = () => window.scrollTo({top:0, behavior:'smooth'});

// ─── STICKY HEADER ───────────────────────────────────────────────────────────
const StickyHeader = ({ lang, setLang, doneR, totalR, breadcrumb }) => {
  const pct = totalR > 0 ? Math.round((doneR / totalR) * 100) : 0;
  return h('div', {style:{position:"sticky", top:0, zIndex:100}},
    // Navy title bar
    h('div', {style:{background:navy, padding:"0 28px", height:50,
      display:"flex", alignItems:"center", justifyContent:"space-between",
      boxShadow:"0 1px 0 rgba(255,255,255,0.08)"}},
      h('span', {style:{color:white, fontSize:14, fontWeight:600,
        flex:1, marginRight:12, whiteSpace:"nowrap", overflow:"hidden",
        textOverflow:"ellipsis"}},
        T("Evaluating AI-Generated Rubrics — Pediatric EM",
          "소아 응급의학 AI 생성 루브릭 평가", lang)),
      h('div', {style:{display:"flex", gap:4}},
        ["en","ko"].map(l =>
          h('button', {key:l, onClick:()=>setLang(l),
            style:{padding:"4px 10px", borderRadius:6, border:"1px solid",
              borderColor: lang===l?"rgba(255,255,255,0.9)":"rgba(255,255,255,0.3)",
              background: lang===l?"rgba(255,255,255,0.18)":"transparent",
              color: lang===l?white:"rgba(255,255,255,0.65)",
              fontSize:12, fontWeight:700, cursor:"pointer", fontFamily:ffs}},
            l==="en"?"EN":"한국어"))
      )
    ),
    // Progress bar — full width, own row, page background for separation
    totalR > 0 && h('div', {style:{background:"#FAFBFC", padding:"5px 0"}},
      h('div', {style:{height:5, background:"#E2E8F0", borderRadius:0, overflow:"hidden"}},
        h('div', {style:{height:"100%", width:pct+"%", background:navyMid,
          borderRadius:"0 99px 99px 0", transition:"width 0.6s ease"}})
      )
    ),
    // Breadcrumb — very light, no borders for clean look
    breadcrumb && h('div', {style:{background:"#FAFBFC",
      padding:"7px 28px", display:"flex", alignItems:"center",
      justifyContent:"space-between"}},
      h('span', {style:{fontSize:13, color:navy}}, breadcrumb),
      h('span', {style:{fontSize:12, color:muted}},
        doneR+" / "+totalR+" "+T("rubrics","기준표", lang))
    )
  );
};

// ─── CONSENT SCREEN ──────────────────────────────────────────────────────────
function ConsentScreen({ onAgree }) {
  const [agreed, setAgreed] = useState(false);
  const lang = useLang();
  const t = (en,ko) => T(en,ko,lang);
  const bp = {fontSize:14, color:txt, lineHeight:1.85, margin:"0 0 14px"};
  const ulp = {fontSize:14, color:txt, lineHeight:1.85, paddingLeft:22, margin:"6px 0 14px"};

  const sections = [
    {n:"1", en:"Purpose of the Study", ko:"연구 목적", body: t(
      h('div',null,
        h('p',{style:bp},"You are invited to participate in a research study examining how pediatric clinicians evaluate and modify assessment rubric frameworks for clinical history-taking generated by large language models (LLMs)."),
        h('p',{style:bp},"The study aims to understand variability among clinicians and the degree of alignment between clinician judgment and AI-generated rubrics.")),
      h('div',null,
        h('p',{style:bp},"본 연구는 대규모 언어모델(LLM)이 생성한 임상 병력 청취 평가 루브릭 프레임워크를 소아 진료 전문가들이 어떻게 평가하고 수정하는지를 분석하기 위한 연구입니다."),
        h('p',{style:bp},"본 연구의 목적은 의료진 간 평가 기준의 변이(variability)를 이해하고, 의료진의 판단과 AI가 생성한 루브릭 간의 정렬 정도(alignment)를 분석하는 것입니다.")))
    },
    {n:"2", en:"Procedures", ko:"연구 절차", body: t(
      h('div',null,
        h('p',{style:bp},"If you agree to participate, you will complete an online survey. You will review rubric frameworks associated with five standardized pediatric emergency clinical vignettes. For each rubric, you will:"),
        h('ul',{style:ulp},
          h('li',null,"A. Indicate whether you agree that each item should be included in the rubric."),
          h('li',null,"B. Rank the items within each domain in order of importance according to your clinical judgment.")),
        h('p',{style:bp},"The survey is expected to take approximately 45–60 minutes to complete.")),
      h('div',null,
        h('p',{style:bp},"연구 참여에 동의하시면 온라인 설문조사를 수행하게 됩니다. 참여자는 소아 응급 상황을 기반으로 한 5개의 표준화된 임상 시나리오와 해당 시나리오에 대한 평가 루브릭을 검토하게 됩니다. 각 루브릭에 대해 다음을 수행합니다:"),
        h('ul',{style:ulp},
          h('li',null,"A. 해당 항목이 평가 기준에 포함되는 것이 적절한지 여부를 표시합니다."),
          h('li',null,"B. 각 영역 내 항목을 임상적 판단에 따라 중요도 순서로 순위를 매겨 주십시오.")),
        h('p',{style:bp},"설문 완료에는 약 45–60분 정도가 소요될 것으로 예상됩니다.")))
    },
    {n:"3", en:"Voluntary Participation and Right to Withdraw", ko:"자발적 참여 및 철회 권리", body: t(
      h('p',{style:bp},"Your participation is entirely voluntary. You may choose not to participate or to withdraw from the study at any time without penalty or loss of benefits to which you are otherwise entitled."),
      h('p',{style:bp},"본 연구 참여는 전적으로 자발적입니다. 참여자는 언제든지 연구 참여를 거부하거나 중단할 수 있으며, 이에 따른 어떠한 불이익도 발생하지 않습니다."))
    },
    {n:"4", en:"Risks and Discomforts", ko:"예상되는 위험 및 불편", body: t(
      h('p',{style:bp},"There are no foreseeable physical or psychological risks associated with participation. The primary burden is the time required to complete the survey and potential survey fatigue."),
      h('p',{style:bp},"본 연구 참여로 인해 예상되는 신체적 또는 심리적 위험은 없습니다. 다만 설문 응답에 소요되는 시간으로 인해 일시적인 설문 피로(survey fatigue)가 발생할 수 있습니다."))
    },
    {n:"5", en:"Benefits", ko:"기대되는 이익", body: t(
      h('p',{style:bp},"There is no direct benefit to you from participating in this study. However, the findings may contribute to improving assessment frameworks and the responsible use of AI in medical education."),
      h('p',{style:bp},"본 연구 참여로 인한 직접적인 개인적 이익은 없습니다. 그러나 연구 결과는 의료 교육에서 AI 기반 평가 프레임워크 개선 및 책임 있는 AI 활용에 기여할 수 있습니다."))
    },
    {n:"6", en:"Confidentiality", ko:"개인정보 보호", body: t(
      h('p',{style:bp},"No patient data will be collected. Your responses will be anonymized at the time of data collection. No identifying information will be included in the analysis or publications resulting from this study. All data will be stored securely and accessed only by the research team in accordance with institutional data protection policies."),
      h('p',{style:bp},"본 연구에서는 환자 정보는 수집되지 않습니다. 응답 데이터는 수집 단계에서 익명화(anonymized) 되며, 연구 분석 및 논문 발표 시 개인을 식별할 수 있는 정보는 포함되지 않습니다. 모든 데이터는 기관의 데이터 보호 정책에 따라 안전하게 저장 및 관리되며 연구팀만 접근할 수 있습니다."))
    },
    {n:"7", en:"Questions", ko:"문의 사항", body: t(
      h('p',{style:bp},"If you have questions about this study, please contact the principal investigator listed above."),
      h('p',{style:bp},"연구에 관한 질문이 있으시면 연구책임자에게 문의하십시오."))
    },
  ];

  return h(PageWrap, null,
    h('div',{style:{textAlign:"center", padding:"48px 0 36px"}},
      h('div',{style:{width:68,height:68,borderRadius:"50%",background:navyL,
        border:"2px solid "+navyBd,display:"flex",alignItems:"center",
        justifyContent:"center",margin:"0 auto 24px"}},
        h('svg',{width:30,height:30,viewBox:"0 0 24 24",fill:"none",stroke:navy,strokeWidth:2,strokeLinecap:"round",strokeLinejoin:"round"},
          h('path',{d:"M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"}),
          h('polyline',{points:"14 2 14 8 20 8"}))),
      h('h1',{style:{fontSize:22,fontWeight:700,color:navy,margin:"0 0 8px",fontFamily:ffs,lineHeight:1.4}},
        t("Evaluating AI-Generated Rubric Frameworks for Clinical History-Taking Assessment",
          "임상 병력 청취 평가를 위한 AI 생성 루브릭 프레임워크 평가")),
    ),
    h(Card,{style:{overflow:"hidden",marginBottom:28}},
      h('div',{style:{background:navy,padding:"22px 32px"}},
        h('p',{style:{color:white,fontSize:15,fontWeight:700,margin:"0 0 10px"}},
          t("Your clinical expertise matters — and so does this research.",
            "귀하의 임상 전문성이 중요합니다 — 그리고 이 연구도 마찬가지입니다.")),
        h('div',null,
          h('p',{style:{color:"rgba(255,255,255,0.85)",fontSize:13,lineHeight:1.7,margin:"0 0 10px"}},
            t("As AI tools begin to shape how clinical competence is assessed, the judgments of experienced pediatric clinicians like you are essential. This study asks a simple but important question: do AI-generated rubrics for clinical history-taking actually reflect how expert clinicians think?",
              "AI 도구가 임상 역량 평가 방식을 변화시키기 시작하는 지금, 귀하와 같은 숙련된 소아 임상의의 판단이 필수적입니다. 이 연구는 단순하지만 중요한 질문을 던집니다: AI가 생성한 임상 병력 청취 루브릭이 실제로 전문 임상의의 사고 방식을 반영하는가?")),
          h('p',{style:{color:"rgba(255,255,255,0.85)",fontSize:13,lineHeight:1.7,margin:0}},
            t("By completing this survey, you are directly contributing to evidence that will guide whether and how AI can responsibly support medical education and assessment. Your responses will help ensure that any AI tools used in training the next generation of clinicians are held to the standards that experienced practitioners like yourself would actually endorse.",
              "이 설문을 완료함으로써 귀하는 AI가 의학 교육 및 평가를 책임감 있게 지원할 수 있는지를 안내할 근거에 직접 기여하게 됩니다. 귀하의 응답은 차세대 임상의 교육에 사용되는 AI 도구가 귀하와 같은 숙련된 전문가가 실제로 지지할 기준을 충족하도록 보장하는 데 도움이 됩니다.")))),
      h('div',{style:{display:"grid",gridTemplateColumns:"1fr 1fr",borderBottom:"1px solid "+cardBd}},
        h('div',{style:{padding:"18px 28px",borderRight:"1px solid "+cardBd}},
          h('p',{style:{fontSize:11,fontWeight:700,color:muted,textTransform:"uppercase",letterSpacing:"0.08em",margin:"0 0 5px"}},t("PRINCIPAL INVESTIGATOR","연구 책임자")),
          h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 3px"}},"Meong Hi Son, MD"),
          h('p',{style:{fontSize:13,color:muted,margin:0,lineHeight:1.5}},t("Department of Emergency Medicine","응급의학과")),
          h('p',{style:{fontSize:13,color:muted,margin:0}},t("Samsung Medical Center","삼성서울병원"))),
        h('div',{style:{padding:"18px 28px"}},
          h('p',{style:{fontSize:11,fontWeight:700,color:muted,textTransform:"uppercase",letterSpacing:"0.08em",margin:"0 0 5px"}},t("STUDY TITLE","연구 제목")),
          h('p',{style:{fontSize:13,color:txt,margin:0,lineHeight:1.6}},
            t("Evaluating Human and AI Variability in Validating AI-Generated Rubric Frameworks for Clinical History-Taking Assessment",
              "임상 병력 청취 평가를 위한 AI 생성 루브릭 프레임워크 검증에서 인간과 AI의 변이성 평가")))
      ),
      h('div',{style:{padding:"8px 28px 0"}},
        sections.map((sec,si) =>
          h('div',{key:sec.n,style:{borderTop:si===0?"none":"1px solid "+cardBd,paddingTop:si===0?16:20,marginTop:si===0?0:20}},
            h('h3',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 12px"}},
              t(sec.n+". "+sec.en, sec.n+". "+sec.ko)),
            sec.body)
        )
      ),
      h('div',{style:{padding:"24px 28px 28px",borderTop:"1px solid "+cardBd,background:"#FAFBFD"}},
        h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 10px"}},
          t("8. Consent Statement","8. 연구 참여 동의")),
        h('p',{style:{fontSize:14,color:txt,lineHeight:1.8,margin:"0 0 10px"}},
          t('By selecting "I agree to participate in this study" below, you confirm that:',
            '아래 "본 연구 참여에 동의합니다"를 선택함으로써 다음 사항을 확인합니다:')),
        h('ul',{style:{fontSize:14,color:txt,lineHeight:1.9,paddingLeft:22,margin:"0 0 20px",listStyleType:"disc"}},
          h('li',null,t("You have read and understood the information above.","위 설명을 읽고 이해하였습니다.")),
          h('li',null,t("You voluntarily agree to participate in this study.","본 연구에 자발적으로 참여하는 것에 동의합니다."))
        ),
        h('label',{style:{display:"flex",alignItems:"flex-start",gap:12,marginBottom:24,cursor:"pointer"}},
          h('input',{type:"checkbox",checked:agreed,onChange:e=>setAgreed(e.target.checked),
            style:{marginTop:3,width:18,height:18,cursor:"pointer",accentColor:navy,flexShrink:0}}),
          h('span',{style:{fontSize:14,fontWeight:600,color:txt,lineHeight:1.5}},
            t("I agree to participate in this study","본 연구 참여에 동의합니다"))
        ),
        h(PrimaryBtn,{onClick:()=>{scrollTop();onAgree();},disabled:!agreed},
          t("Continue →","계속 →"))
      )
    )
  );
}

// ─── INSTRUCTIONS SCREEN ─────────────────────────────────────────────────────
function InstrScreen({ onStart }) {
  const lang = useLang();
  const t = (en,ko) => T(en,ko,lang);
  const steps = [
    {num:1,
      en:"Review the clinical vignette", ko:"임상 사례 검토",
      descEn:"Read the pediatric emergency case — including chief complaint, clinical history, vital signs, and physical exam findings. This provides the context for evaluating the rubric.",
      descKo:"주 호소, 임상 병력, 활력 징후, 신체 검진 소견을 포함한 소아 응급 사례를 읽습니다. 이는 루브릭 평가의 맥락을 제공합니다."},
    {num:2,
      en:"Section A — Item inclusion", ko:"섹션 A — 항목 포함 여부",
      descEn:"For each rubric item, select Agree if it should be included in an ideal rubric, or Disagree if not. You may add an optional comment.",
      descKo:"각 루브릭 항목에 대해 이상적인 루브릭에 포함되어야 한다면 동의, 그렇지 않다면 비동의를 선택합니다. 선택적 의견을 추가할 수 있습니다."},
    {num:3,
      en:"Section B — Item ranking", ko:"섹션 B — 항목 순위",
      descEn:"Rank the items within each domain in order of importance. Drag and drop or use the arrow buttons to reorder them.",
      descKo:"각 영역 내 항목을 임상적 판단에 따라 중요도 순서로 순위를 매겨 주십시오. 드래그 앤 드롭 또는 화살표 버튼을 사용하여 순서를 조정합니다."},
    {num:4,
      en:"Repeat for all 5 cases", ko:"5개 사례 모두 반복",
      descEn:"Complete Sections A and B for each rubric across all 5 pediatric emergency cases. Each case has 4 rubrics generated by different AI models.",
      descKo:"5개의 소아 응급 사례 전체에 걸쳐 각 루브릭에 대해 섹션 A와 B를 완료합니다. 각 사례에는 서로 다른 AI 모델이 생성한 4개의 루브릭이 있습니다."},
  ];
  return h(PageWrap, null,
    h('div',{style:{textAlign:"center",marginBottom:36}},
      h('h1',{style:{fontSize:24,fontWeight:700,color:navy,fontFamily:ffs,marginBottom:10}},t("Instructions","지침")),
      h('p',{style:{fontSize:15,color:muted,lineHeight:1.6}},t("Please read carefully before starting.","시작 전에 주의 깊게 읽어주세요."))),
    h(Card,{style:{padding:"22px 32px",marginBottom:20}},
      h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 10px"}},t("What you'll be reviewing:","검토하실 내용:")),
      h('p',{style:{fontSize:14,color:txt,lineHeight:1.8,margin:0}},
        t("An AI was given 5 pediatric emergency case vignettes and asked to generate assessment rubrics for evaluating a clinician's history-taking performance. You will review whether the AI's rubric items are appropriate and how they should be ranked in importance.",
          "4개의 소아 응급 사례 각각에 대해 4개의 AI 생성 루브릭 프레임워크 (총 16개). 각 루브릭은 두 파트로 구성됩니다: 항목 평가(파트 A)와 항목 순위 매기기(파트 B)."))),
    steps.map(s =>
      h(Card,{key:s.num,style:{padding:"16px 20px",marginBottom:10,display:"flex",gap:16,alignItems:"flex-start"}},
        h('div',{style:{width:30,height:30,borderRadius:"50%",background:navy,
          display:"flex",alignItems:"center",
          justifyContent:"center",flexShrink:0,marginTop:1}},
          h('span',{style:{fontSize:13,fontWeight:700,color:white,fontFamily:ffs}},s.num)),
        h('div',null,
          h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 4px",lineHeight:1.4}},t(s.en,s.ko)),
          h('p',{style:{fontSize:13,color:txt,lineHeight:1.65,margin:0}},t(s.descEn,s.descKo))))
    ),
    h(Card,{style:{padding:"18px 24px",marginBottom:32,background:amberBg,border:"1px solid "+amberBd}},
      h('div',{style:{display:"flex",gap:12,alignItems:"flex-start"}},
        h('span',{style:{fontSize:18,flexShrink:0,marginTop:2}},"💡"),
        h('div',null,
          h('p',{style:{fontSize:14,fontWeight:700,color:"#92400e",margin:"0 0 6px"}},t("Keep in mind","참고하세요")),
          h('ul',{style:{fontSize:14,color:"#78350f",margin:0,paddingLeft:18,lineHeight:1.8}},
            h('li',null,t("There are no right or wrong answers. Variation between clinicians is expected — measuring that variation is precisely what this research aims to do. Please respond based on your honest professional judgment.","정답이나 오답은 없습니다. 의료진 간의 차이는 예상되며, 그 변이를 측정하는 것이 바로 본 연구의 목적입니다. 귀하의 솔직한 전문가적 판단에 따라 응답해 주십시오.")),
            h('li',null,t("Each item includes the AI's reasoning for why it was included. This is for reference only — you are not required to agree with it.","각 항목에는 해당 항목이 포함된 AI의 근거가 포함되어 있습니다. 이는 참고용이며 동의할 필요는 없습니다.")))))),
    h(PrimaryBtn,{onClick:()=>{scrollTop();onStart();}},t("Begin Survey →","설문 시작 →"))
  );
}

// ─── VIGNETTE SIDEBAR ────────────────────────────────────────────────────────
function VignetteSidebar({ caseData }) {
  const lang = useLang();
  const t = (en,ko) => T(en,ko,lang);
  return h('div',{style:{width:336,flexShrink:0,position:"sticky",top:90}},
    h(Card,{style:{overflow:"hidden",display:"flex",flexDirection:"column",
      maxHeight:"calc(100vh - 110px)"}},
      h('div',{style:{padding:"12px 16px",borderBottom:"1px solid "+cardBd,
        background:navyL,flexShrink:0}},
        h('p',{style:{fontSize:13,fontWeight:700,color:navy,margin:0,lineHeight:1.4}},
          t(caseData.en, caseData.ko))),
      h('div',{style:{overflowY:"auto",flex:1,minHeight:0}},
        caseData.vignette.rows.map((r,i) =>
          h('div',{key:i,style:{padding:"9px 16px",borderBottom:"1px solid "+cardBd}},
            h('p',{style:{fontSize:12,fontWeight:700,color:muted,
              textTransform:"uppercase",letterSpacing:"0.04em",margin:"0 0 2px"}},
              t(r.en,r.ko)),
            h('p',{style:{fontSize:13,color:txt,lineHeight:1.6,margin:0}},
              t(r.val_en,r.val_ko)))
        ),
        h('div',{style:{padding:"9px 16px",borderBottom:"1px solid "+cardBd}},
          h('p',{style:{fontSize:12,fontWeight:700,color:muted,
            textTransform:"uppercase",letterSpacing:"0.04em",margin:"0 0 6px"}},
            t("Vital Signs","활력 징후")),
          caseData.vignette.vitals.map((v,i) =>
            h('div',{key:i,style:{display:"flex",justifyContent:"space-between",
              alignItems:"flex-start",fontSize:13,padding:"3px 0",
              borderTop:i>0?"1px solid "+cardBd:"none"}},
              h('span',{style:{color:muted,flexShrink:0,marginRight:8}},t(v.en,v.ko)),
              h('span',{style:{color:txt,fontWeight:500,textAlign:"right"}},t(v.val_en,v.val_ko)))
          )
        ),
        h('div',{style:{padding:"9px 16px"}},
          h('p',{style:{fontSize:12,fontWeight:700,color:muted,
            textTransform:"uppercase",letterSpacing:"0.04em",margin:"0 0 6px"}},
            t("Physical Exam","신체 검진")),
          caseData.vignette.exam.map((e,i) =>
            h('div',{key:i,style:{fontSize:13,padding:"3px 0",
              borderTop:i>0?"1px solid "+cardBd:"none",lineHeight:1.5}},
              h('span',{style:{color:muted,fontWeight:600}},t(e.en,e.ko)+": "),
              h('span',{style:{color:txt}},t(e.val_en,e.val_ko)))
          )
        )
      )
    )
  );
}

// ─── PART A SCREEN ───────────────────────────────────────────────────────────
function PartAScreen({ caseData, rubric, onNext, onBack, draftAnswers, onDraftChange }) {
  const lang = useLang();
  const t = (en,ko) => T(en,ko,lang);
  const [partA, setPartA] = useState(()=>draftAnswers.answers||{});
  const [comments, setComments] = useState(()=>draftAnswers.comments||{});

  const allItems = [...rubric.d1, ...rubric.d2];
  const totalItems = allItems.length;
  const answeredItems = Object.keys(partA).length;
  const allAnswered = answeredItems === totalItems;
  const itemRefs = React.useRef({});
  const [highlightId, setHighlightId] = useState(null);

  const goToFirst = () => {
    const firstMissing = allItems.find(item => partA[item.id] === undefined);
    if (!firstMissing) return;
    setHighlightId(firstMissing.id);
    const el = itemRefs.current[firstMissing.id];
    if (el) { el.scrollIntoView({behavior:"smooth", block:"center"}); }
    setTimeout(() => setHighlightId(null), 5000);
  };

  const ItemRow = ({item, idx, showTop}) => {
    const ans = partA[item.id];
    const raw = t(item.en, item.ko);
    // Split on first colon: "Item N. Name: description" → bold name + normal body
    const colonIdx = raw.indexOf(": ");
    const lbl = colonIdx > -1 ? raw.slice(0, colonIdx) : raw;
    const body = colonIdx > -1 ? raw.slice(colonIdx+2) : "";
    const isHighlighted = highlightId === item.id;
    return h('div',{ref: el => { itemRefs.current[item.id] = el; },
      style:{
      padding:"20px 22px",
      borderTop: showTop ? "1px solid "+cardBd : "none",
      background: isHighlighted ? "#FFF3CD" : ans===true ? greenBg : ans===false ? redBg : white,
      outline: isHighlighted ? "2px solid #F59E0B" : "none",
      outlineOffset: "-2px",
      transition:"background 0.3s, outline 0.3s"}},
      isHighlighted && h('p',{style:{fontSize:12,fontWeight:700,color:"#92400e",
        margin:"0 0 8px",display:"flex",alignItems:"center",gap:6}},
        "⚠ "+t("Please answer this item before continuing.","계속하기 전에 이 항목에 답해 주세요.")),
      h('p',{style:{fontSize:14,fontWeight:700,color:navy,lineHeight:1.4,margin:"0 0 4px"}},lbl),
      body && h('p',{style:{fontSize:13,color:txt,lineHeight:1.65,margin:"0 0 14px"}},body),
      h('div',{style:{
        background: ans===true?"#dcfce7" : ans===false?"#fee2e2" : "#F0F4FA",
        border:"1px solid "+(ans===true?greenBd:ans===false?redBd:cardBd),
        borderRadius:8,padding:"10px 14px",marginBottom:14}},
        h('p',{style:{fontSize:12,fontWeight:700,
          color:ans===true?green:ans===false?red:muted,
          textTransform:"uppercase",letterSpacing:"0.05em",margin:"0 0 4px"}},
          t("Explanation","설명")),
        h('p',{style:{fontSize:13,color:ans===true?"#14532d":ans===false?"#4c0519":"#374151",
          lineHeight:1.65,margin:0}},t(item.xEn,item.xKo))),
      h('div',{style:{display:"flex",gap:10,marginBottom:ans!==undefined?12:0}},
        h('button',{onClick:()=>{setPartA(p=>{const n={...p,[item.id]:true}; onDraftChange(item.id,true,comments); return n;})},
          style:{flex:1,padding:"11px 0",borderRadius:8,fontSize:14,fontWeight:600,
            border:"2px solid "+(ans===true?green:cardBd),
            background:ans===true?greenBg:white,color:ans===true?green:muted,
            cursor:"pointer",transition:"all 0.15s"}},
          "✓ "+t("Agree","동의")),
        h('button',{onClick:()=>{setPartA(p=>{const n={...p,[item.id]:false}; onDraftChange(item.id,false,comments); return n;})},
          style:{flex:1,padding:"11px 0",borderRadius:8,fontSize:14,fontWeight:600,
            border:"2px solid "+(ans===false?red:cardBd),
            background:ans===false?redBg:white,color:ans===false?red:muted,
            cursor:"pointer",transition:"all 0.15s"}},
          "✗ "+t("Disagree","비동의"))),
      ans!==undefined && h('textarea',{
        placeholder:t("Optional comment for this item…","이 항목에 대한 선택적 의견…"),
        value:comments[item.id]||"",
        onChange:e=>setComments(c=>{const n={...c,[item.id]:e.target.value}; onDraftChange(item.id,partA[item.id],n); return n;}),
        style:{width:"100%",padding:"9px 12px",fontSize:14,
          border:"1px solid "+cardBd,borderRadius:8,resize:"vertical",
          fontFamily:ffs,boxSizing:"border-box",minHeight:60,
          background:"rgba(255,255,255,0.8)"}})
    );
  };

  const Domain = ({items, label, desc, pts}) =>
    h('div',{style:{marginBottom:24}},
      h('div',{style:{background:navyL,border:"1px solid "+navyBd,
        borderRadius:"10px 10px 0 0",padding:"12px 20px",
        display:"flex",justifyContent:"space-between",alignItems:"flex-start"}},
        h('div',{style:{flex:1}},
          h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 3px"}},label),
          desc && h('p',{style:{fontSize:13,color:muted,margin:0,lineHeight:1.5}},desc)),
        h('span',{style:{fontSize:13,fontWeight:700,color:navyMid,flexShrink:0,marginLeft:12,marginTop:2}},
          pts+t(" pts"," 점"))),
      h('div',{style:{border:"1px solid "+cardBd,borderTop:"none",
        borderRadius:"0 0 10px 10px",overflow:"hidden"}},
        items.map((item,idx)=>h(ItemRow,{key:item.id,item,idx,showTop:idx>0})))
    );

  const d1label = t("Domain 1: General Clinical History-Taking","영역 1: 일반 임상 병력 청취");
  const d2label = t("Domain 2: Case-Specific Diagnostic History","영역 2: 사례별 진단 추론");

  return h('div',{style:{flex:1,minWidth:0}},
    h(Card,{style:{padding:"16px 22px",marginBottom:20,background:navyL,border:"1px solid "+navyBd,boxShadow:"none"}},
      h('div',{style:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12}},
        h('div',null,
          h('p',{style:{fontSize:16,fontWeight:700,color:navy,margin:"0 0 4px"}},
            t(rubric.label_en,rubric.label_ko)+" — "+t("Part A","파트 A")),
          h('p',{style:{fontSize:13,color:muted,margin:0}},
            t("Select Agree or Disagree for each item. You may add an optional comment.",
              "각 항목에 동의 또는 비동의를 선택하세요. 선택적 의견을 추가할 수 있습니다."))),
        h('div',{style:{textAlign:"right",flexShrink:0}},
          h('p',{style:{fontSize:11,color:muted,margin:"0 0 2px"}},t("Total","총점")),
          h('p',{style:{fontSize:18,fontWeight:700,color:navyMid,margin:0}},
            (rubric.d1pts+rubric.d2pts)+t(" pts"," 점")))),
      (rubric.threshold_en||rubric.rationale_en) &&
        h('div',{style:{background:amberBg,border:"1px solid "+amberBd,
          borderRadius:8,padding:"10px 14px",marginTop:14,
          display:"flex",gap:10,alignItems:"flex-start"}},
          h('span',{style:{fontSize:15,flexShrink:0}},"ℹ️"),
          h('p',{style:{fontSize:13,color:"#78350f",lineHeight:1.65,margin:0}},
            t(rubric.threshold_en||rubric.rationale_en,
              rubric.threshold_ko||rubric.rationale_ko)))
    ),
    h(Domain,{items:rubric.d1,label:d1label,desc:t(rubric.d1desc_en||'',rubric.d1desc_ko||''),pts:rubric.d1pts}),
    h(Domain,{items:rubric.d2,label:d2label,desc:t(rubric.d2desc_en||'',rubric.d2desc_ko||''),pts:rubric.d2pts}),
    h('div',{style:{display:"flex",gap:12,alignItems:"center"}},
      onBack && h('button',{onClick:onBack,
        style:{padding:"14px 20px",borderRadius:10,border:"2px solid "+navy,
          background:white,color:navy,fontSize:15,fontWeight:600,
          cursor:"pointer",whiteSpace:"nowrap",flexShrink:0}},
        "← "+t("Back","이전")),
      h(PrimaryBtn,{
        onClick:()=>{ if(allAnswered){ onNext({partA,comments}); } else { goToFirst(); } }},
        t("Continue to Part B →","파트 B로 계속 →"))
    )
  );
}

// ─── PART B SCREEN ───────────────────────────────────────────────────────────
function PartBScreen({ caseData, rubric, ci, ri, isLast, onSubmit, partAData, onBack, bDraft, onBDraftChange }) {
  const lang = useLang();
  const t = (en,ko) => T(en,ko,lang);
  const [d1Order, setD1Order] = useState(()=>bDraft?.d1Order||[...rubric.d1].sort((a,b)=>b.pts-a.pts).map(i=>i.id));
  const [d2Order, setD2Order] = useState(()=>bDraft?.d2Order||[...rubric.d2].sort((a,b)=>b.pts-a.pts).map(i=>i.id));
  const [finalCmt, setFinalCmt] = useState(bDraft?.finalCmt||"");
  React.useEffect(()=>{ onBDraftChange(d1Order,d2Order,finalCmt); },[d1Order,d2Order,finalCmt]);

  const moveItem = (order, setOrder, idx, dir) => {
    const next=[...order]; const to=idx+dir;
    if(to<0||to>=next.length) return;
    [next[idx],next[to]]=[next[to],next[idx]];
    setOrder(next);
  };

  // Next button label — no "submit", just navigation
  const nextLabel = () => {
    if(isLast) return t("Finish Survey →","설문 완료 →");
    const nr=ri+1;
    const nrInCase = nr < caseData.rubrics.length;
    if(nrInCase) return t("Next Rubric →","다음 기준표 →");
    return t("Next Case →","다음 사례 →");
  };

  const SortableList = ({items, order, setOrder}) => {
    const [dragging, setDragging] = React.useState(null);
    const [overIdx, setOverIdx]   = React.useState(null);
    const itemEls = React.useRef({});
    // Keep latest dragging/overIdx in refs so window handlers can read current values
    const draggingRef = React.useRef(null);
    const overIdxRef  = React.useRef(null);
    const orderRef    = React.useRef(order);
    React.useEffect(() => { orderRef.current = order; }, [order]);

    const computeOverIdx = (clientY, snaps, fromIdx) => {
      let bestIdx = fromIdx, bestDist = Infinity;
      orderRef.current.forEach((id2, i) => {
        const snap = snaps[id2];
        if(!snap) return;
        const mid = snap.top + snap.height / 2;
        const dist = Math.abs(clientY - mid);
        if(dist < bestDist) { bestDist = dist; bestIdx = i; }
      });
      return bestIdx;
    };

    const onPointerDown = (e, id) => {
      if(e.button !== undefined && e.button !== 0) return;
      const el = itemEls.current[id];
      const rect = el ? el.getBoundingClientRect() : {top:0, height:60};
      const grabOffsetY = e.clientY - rect.top;
      const snaps = {};
      Object.entries(itemEls.current).forEach(([id2, el2]) => {
        if(el2) { const r = el2.getBoundingClientRect(); snaps[id2] = {top:r.top, height:r.height}; }
      });
      const fromIdx = orderRef.current.indexOf(id);
      const drag = {id, startY:e.clientY, currentY:e.clientY,
        height:rect.height, grabOffsetY, snaps, fromIdx};
      draggingRef.current = drag;
      overIdxRef.current  = fromIdx;
      setDragging(drag);
      setOverIdx(fromIdx);
      e.preventDefault();
    };

    // Attach move/up to window so coordinates are always raw viewport
    React.useEffect(() => {
      const onMove = (e) => {
        const drag = draggingRef.current;
        if(!drag) return;
        const clientY = e.clientY !== undefined ? e.clientY : e.touches?.[0]?.clientY;
        if(clientY === undefined) return;
        const updated = {...drag, currentY: clientY};
        draggingRef.current = updated;
        setDragging(updated);
        const newOver = computeOverIdx(clientY, drag.snaps, drag.fromIdx);
        overIdxRef.current = newOver;
        setOverIdx(newOver);
      };
      const onUp = () => {
        const drag = draggingRef.current;
        const oi   = overIdxRef.current;
        if(!drag) return;
        if(oi !== null && oi !== drag.fromIdx) {
          setOrder(prev => {
            const next = [...prev];
            next.splice(drag.fromIdx, 1);
            next.splice(oi, 0, drag.id);
            return next;
          });
        }
        draggingRef.current = null;
        overIdxRef.current  = null;
        setDragging(null);
        setOverIdx(null);
      };
      window.addEventListener('pointermove', onMove);
      window.addEventListener('pointerup',   onUp);
      return () => {
        window.removeEventListener('pointermove', onMove);
        window.removeEventListener('pointerup',   onUp);
      };
    }, []);

    const dy = dragging ? dragging.currentY - dragging.startY : 0;
    const dragIdx = dragging ? order.indexOf(dragging.id) : -1;

    return h('div', {style:{position:"relative"}},
      order.map((id, idx) => {
        const item = items.find(i => i.id === id); if(!item) return null;
        const raw = t(item.en, item.ko);
        // Split on first colon: "Item N. Name: description" → name + desc
        const colonIdx = raw.indexOf(": ");
        const lbl = colonIdx>-1 ? raw.slice(0, colonIdx) : raw;
        const desc = colonIdx>-1 ? raw.slice(colonIdx+2).trim() : "";
        const isDragging = dragging && dragging.id === id;
        // placeholder gap: show above/below based on overIdx
        const showGapAbove = dragging && !isDragging && overIdx === idx && dragIdx > idx;
        const showGapBelow = dragging && !isDragging && overIdx === idx && dragIdx < idx;
        return h('div', {key:id, style:{marginBottom:6}},
          // gap placeholder above
          showGapAbove && h('div', {style:{height:dragging.height+6, background:navyL,
            border:"2px dashed "+navyBd, borderRadius:8, marginBottom:6,
            transition:"height 0.1s"}}),
          // the actual item
          h('div', {
            ref: el => { itemEls.current[id] = el; },
            onPointerDown: e => onPointerDown(e, id),
            style:{
              display:"flex", alignItems:"flex-start", gap:10,
              padding:"12px 14px",
              background: isDragging ? navyL : white,
              border:"1px solid "+(isDragging ? navyBd : cardBd),
              borderRadius:8,
              boxShadow: isDragging
                ? "0 8px 24px rgba(27,43,94,0.22)"
                : "0 1px 3px rgba(0,0,0,0.05)",
              transform: isDragging ? "translate(0,"+dy+"px)" : "none",
              transition: isDragging ? "box-shadow 0.1s" : "transform 0.15s, box-shadow 0.15s",
              opacity: isDragging ? 0.95 : (dragging && !isDragging ? 0.6 : 1),
              cursor: isDragging ? "grabbing" : "grab",
              userSelect:"none",
              zIndex: isDragging ? 10 : 1,
              position: "relative",
              touchAction:"none"
            }},
            h('div',{style:{display:"flex",flexDirection:"column",alignItems:"center",
              gap:4,flexShrink:0,paddingTop:4}},
              h('div',{style:{color:muted,fontSize:16,userSelect:"none",
                lineHeight:1,letterSpacing:"-1px"}},"⠿"),
              h('span',{style:{fontSize:12,fontWeight:700,color:navyMid,
                background:navyL,borderRadius:5,padding:"2px 6px",
                whiteSpace:"nowrap"}},"#"+(idx+1))),
            h('div',{style:{flex:1,paddingTop:2}},
              h('p',{style:{fontSize:14,color:navy,fontWeight:700,
                lineHeight:1.4,margin:"0 0 "+(desc?"3px":"0")}},lbl),
              desc && h('p',{style:{fontSize:13,color:muted,margin:0,lineHeight:1.5}},desc)),
            h('div',{style:{display:"flex",flexDirection:"column",gap:3,flexShrink:0,paddingTop:8}},
              h('button',{onClick:()=>moveItem(order,setOrder,idx,-1),disabled:idx===0,
                style:{padding:"3px 9px",fontSize:13,border:"1px solid "+cardBd,
                  borderRadius:5,background:white,cursor:"pointer",
                  opacity:idx===0?0.25:1,lineHeight:1.2}},"▲"),
              h('button',{onClick:()=>moveItem(order,setOrder,idx,1),
                disabled:idx===order.length-1,
                style:{padding:"3px 9px",fontSize:13,border:"1px solid "+cardBd,
                  borderRadius:5,background:white,cursor:"pointer",
                  opacity:idx===order.length-1?0.25:1,lineHeight:1.2}},"▼"))
          ),
          // gap placeholder below
          showGapBelow && h('div', {style:{height:dragging.height+6, background:navyL,
            border:"2px dashed "+navyBd, borderRadius:8, marginTop:0,
            transition:"height 0.1s"}})
        );
      })
    );
  };

  const DomainRank = ({items, order, setOrder, label}) =>
    h('div',{style:{marginBottom:28}},
      h('div',{style:{background:navyL,border:"1px solid "+navyBd,
        borderRadius:"10px 10px 0 0",padding:"12px 20px"}},
        h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:0}},label)),
      h('div',{style:{border:"1px solid "+cardBd,borderTop:"none",
        borderRadius:"0 0 10px 10px",padding:"14px",background:"#FAFBFD"}},
        h(SortableList,{items,order,setOrder}))
    );

  return h('div',{style:{flex:1,minWidth:0}},
    h(Card,{style:{padding:"16px 22px",marginBottom:8,background:navyL,border:"1px solid "+navyBd,boxShadow:"none"}},
      h('p',{style:{fontSize:16,fontWeight:700,color:navy,margin:"0 0 6px"}},
        t(rubric.label_en,rubric.label_ko)+" — "+t("Part B","파트 B")),
      h('p',{style:{fontSize:13,color:muted,margin:0}},
        t("Drag and drop items to reorder, or use ▲ ▼ arrows.",
          "항목을 드래그하거나 ▲ ▼ 화살표로 순서를 바꾸세요."))
    ),
    h(DomainRank,{items:rubric.d1,order:d1Order,setOrder:setD1Order,
      label:t("Domain 1: General Clinical History-Taking","영역 1: 일반 임상 병력 청취")}),
    h(DomainRank,{items:rubric.d2,order:d2Order,setOrder:setD2Order,
      label:t("Domain 2: Case-Specific Diagnostic History","영역 2: 사례별 진단 추론")}),
    h(Card,{style:{padding:"20px 22px",marginBottom:20}},
      h('p',{style:{fontSize:14,fontWeight:700,color:navy,margin:"0 0 10px"}},
        t("Overall Comment (optional)","전반적인 의견 (선택사항)")),
      h('textarea',{
        placeholder:t("Any comments or suggestions for this rubric?","이 루브릭에 대한 의견이나 제안이 있으신가요?"),
        value:finalCmt,onChange:e=>setFinalCmt(e.target.value),
        style:{width:"100%",padding:"12px 14px",fontSize:14,
          border:"1px solid "+cardBd,borderRadius:8,resize:"vertical",
          fontFamily:ffs,boxSizing:"border-box",minHeight:80}})
    ),
    h('div',{style:{display:"flex",gap:12,alignItems:"center"}},
      h('button',{onClick:onBack,
        style:{padding:"14px 20px",borderRadius:10,border:"2px solid "+navy,
          background:white,color:navy,fontSize:15,fontWeight:600,
          cursor:"pointer",whiteSpace:"nowrap",flexShrink:0}},
        "← "+t("Back","이전")),
      h(PrimaryBtn,{
        onClick:()=>{ onSubmit(rubric.id,{...partAData,d1Order,d2Order,finalCmt}); scrollTop(); }},
        nextLabel())
    )
  );
}

// ─── DONE SCREEN (two states: pre-submit and post-submit) ─────────────────────
function DoneScreen({ responses, preSubmitState, onBack }) {
  const lang = useLang();
  const t = (en,ko) => T(en,ko,lang);
  // preSubmitState: if true, show pre-submit UI (used by preview)
  const [status, setStatus] = useState(preSubmitState ? "idle" : "idle");
  const [pid] = useState(()=>"P-"+Math.random().toString(36).slice(2,8).toUpperCase());
  const blob = new Blob([JSON.stringify(responses,null,2)],{type:"application/json"});
  const url = URL.createObjectURL(blob);

  const submit = async () => {
    setStatus("sending");
    try {
      const rows=[];
      for(const [rubricId,rd] of Object.entries(responses)){
        const parts=rubricId.split("-");
        const caseNo=parseInt(parts[0]), rubricNo=parseInt(parts[1]);
        const rubricLabel="C"+caseNo+"-R"+rubricNo; // e.g. "C1-R2" — unambiguous
        const base={participant_id:pid,lang,case_no:caseNo,rubric_no:rubricNo,
          rubric_id:rubricLabel,overall_comment:rd.finalCmt||""};
        // Agreement rows — one per item
        for(const [itemId,agreed] of Object.entries(rd.partA||{})){
          rows.push({...base,item_id:itemId,agreed,
            comment:(rd.comments||{})[itemId]||"",
            domain:null,rank:null});
        }
        // Ranking rows — one per item per domain
        (rd.d1Order||[]).forEach((itemId,i)=>{
          rows.push({...base,item_id:itemId,agreed:null,comment:"",
            domain:"d1",rank:i+1});
        });
        (rd.d2Order||[]).forEach((itemId,i)=>{
          rows.push({...base,item_id:itemId,agreed:null,comment:"",
            domain:"d2",rank:i+1});
        });
      }
      if(rows.length===0) return;
      const res=await fetch(SUPABASE_URL+"/rest/v1/responses",{
        method:"POST",
        headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY,
          "Authorization":"Bearer "+SUPABASE_KEY,"Prefer":"return=minimal"},
        body:JSON.stringify(rows)
      });
      if(res.ok) { setStatus("success"); try{localStorage.removeItem(LS_KEY);}catch(e){} }
      else { console.error(await res.text()); setStatus("error"); }
    } catch(e){ console.error(e); setStatus("error"); }
  };

  // ── POST-SUBMIT (success) ───────────────────────────────────────────────────
  if(status==="success") return h(PageWrap,null,
    h('div',{style:{textAlign:"center",padding:"64px 0 48px"}},
      h('div',{style:{width:80,height:80,borderRadius:"50%",
        background:"linear-gradient(135deg,"+green+",#059669)",
        margin:"0 auto 28px",display:"flex",alignItems:"center",justifyContent:"center"}},
        h('svg',{width:38,height:38,viewBox:"0 0 24 24",fill:"none",
          stroke:white,strokeWidth:2.5,strokeLinecap:"round",strokeLinejoin:"round"},
          h('path',{d:"M20 6L9 17l-5-5"}))),
      h('h1',{style:{fontSize:26,fontWeight:700,color:navy,margin:"0 0 14px",fontFamily:ffs}},
        t("Your responses have been recorded.","응답이 기록되었습니다.")),
      h('p',{style:{fontSize:15,color:muted,lineHeight:1.75,maxWidth:480,margin:"0 auto 32px"}},
        t("Thank you for completing this survey. Your clinical expertise and time are genuinely appreciated — responses like yours are what make this research meaningful.",
          "이 설문을 완료해 주셔서 감사합니다. 귀하의 임상 전문성과 시간은 진심으로 소중하며, 귀하와 같은 응답이 이 연구를 의미 있게 만들어 줍니다.")),
      h('p',{style:{fontSize:14,color:muted}},
        t("Participant ID: ","참여자 ID: "),
        h('strong',{style:{color:navy,marginLeft:4}},pid)),
      h('div',{style:{marginTop:24}},
        h('a',{href:url,download:"rubric_responses_"+pid+".json",
          style:{color:navyMid,fontSize:14,fontWeight:600,textDecoration:"underline"}},
          t("Download a copy of your responses","응답 사본 다운로드")))
    )
  );

  // ── PRE-SUBMIT (idle / sending / error) ─────────────────────────────────────
  return h(PageWrap,null,
    h('div',{style:{textAlign:"center",padding:"48px 0 36px"}},
      h('h1',{style:{fontSize:26,fontWeight:700,color:navy,margin:"0 0 12px",fontFamily:ffs}},
        t("You've reached the end of the survey.","설문의 끝에 도달하셨습니다.")),
      h('p',{style:{fontSize:15,color:muted,lineHeight:1.75,maxWidth:500,margin:"0 auto"}},
        t("When you're ready, click the button below to submit your responses.",
          "준비가 되시면 아래 버튼을 클릭하여 응답을 제출해 주세요."))
    ),
    h(Card,{style:{padding:"32px 36px"}},
      h('p',{style:{fontSize:14,color:muted,textAlign:"center",margin:"0 0 24px"}},
        t("Participant ID: ","참여자 ID: "),
        h('strong',{style:{color:navy,fontSize:15,marginLeft:4}},pid)),
      status==="idle" && h('div',null,
        h(PrimaryBtn,{onClick:submit},t("Submit Responses →","응답 제출 →")),
        h('div',{style:{textAlign:"center",marginTop:14}},
          h('button',{onClick:onBack,
            style:{background:"none",border:"none",color:muted,fontSize:14,
              cursor:"pointer",textDecoration:"underline",fontFamily:ffs}},
            "← "+t("Back to last rubric","마지막 루브릭으로 돌아가기")))
      ),
      status==="sending" && h('div',{style:{textAlign:"center",padding:"16px",
        background:navyL,borderRadius:10,color:navy,fontSize:15,fontWeight:600}},
        t("Sending…","전송 중…")),
      status==="error" && h('div',null,
        h('div',{style:{padding:"14px",marginBottom:14,background:redBg,
          border:"1px solid "+redBd,borderRadius:10,color:red,fontSize:14,textAlign:"center"}},
          t("Something went wrong with your submission. You can try submitting again, or download a backup copy of your responses and contact the research team.",
            "제출 중 문제가 발생했습니다. 다시 시도하거나, 응답 사본을 다운로드하여 연구팀에 연락해 주세요.")),
        h(PrimaryBtn,{onClick:submit},t("Try again →","다시 시도 →"))),
      h('div',{style:{borderTop:"1px solid "+cardBd,paddingTop:20,marginTop:24,
        textAlign:"center"}},
        h('a',{href:url,download:"rubric_responses_"+pid+".json",
          style:{color:muted,fontSize:13,textDecoration:"underline"}},
          "📥 "+t("Download a copy of your responses","응답 백업 사본 다운로드")))
    )
  );
}

// ─── MAIN APP ────────────────────────────────────────────────────────────────
const LS_KEY = "rubric_survey_session_v1";

function App() {
  // ── Restore from localStorage if available ──────────────────────────────
  const saved = (() => { try { const s=localStorage.getItem(LS_KEY); return s?JSON.parse(s):null; } catch(e){return null;} })();

  const [lang, setLang] = useState(saved?.lang || "en");
  const [step, setStep] = useState(saved?.step || "consent");
  const [ci, setCi] = useState(saved?.ci || 0);
  const [ri, setRi] = useState(saved?.ri || 0);
  const [partAData, setPartAData] = useState(saved?.partAData || null);
  const [partADraft, setPartADraft] = useState(saved?.partADraft || {});
  const [partBDraft, setPartBDraft] = useState(saved?.partBDraft || {});
  const [responses, setResponses] = useState(saved?.responses || {});

  const totalR = CASES.reduce((s,c)=>s+c.rubrics.length,0);
  const doneR  = CASES.slice(0,ci).reduce((s,c)=>s+c.rubrics.length,0)+ri;
  const curCase   = CASES[ci];
  const curRubric = curCase ? curCase.rubrics[ri] : null;

  // ── Autosave to localStorage on every state change ──────────────────────
  React.useEffect(() => {
    if (step === "consent") return; // don't save before they start
    try {
      localStorage.setItem(LS_KEY, JSON.stringify({lang,step,ci,ri,partAData,partADraft,partBDraft,responses}));
    } catch(e) {}
  }, [lang, step, ci, ri, partAData, responses]);

  const goPartB = useCallback((aData)=>{ setPartAData(aData); setStep("partB"); scrollTop(); },[]);
  const goBack = useCallback(()=>{
    // If on partA of a non-first rubric, go to partB of previous rubric
    if(ri > 0){ setRi(ri-1); setStep("partB"); scrollTop(); }
    else if(ci > 0){ setCi(ci-1); setRi(CASES[ci-1].rubrics.length-1); setStep("partB"); scrollTop(); }
    else { setStep("instr"); scrollTop(); }
  },[ci,ri]);
  const submitRubric = useCallback((id,data)=>{
    setResponses(r=>({...r,[id]:data}));
    setPartADraft(d=>{ const n={...d}; delete n[id]; return n; });
    setPartBDraft(d=>{ const n={...d}; delete n[id]; return n; });
    const nr=ri+1;
    if(nr<curCase.rubrics.length){ setRi(nr); setStep("partA"); }
    else { const nc=ci+1; if(nc<CASES.length){setCi(nc);setRi(0);setStep("partA");}else setStep("done"); }
    scrollTop();
  },[ci,ri,curCase]);

  const breadcrumb = (step==="partA"||step==="partB") && curCase && curRubric
    ? h('span',null,
        T("Case "+(ci+1)+" of "+CASES.length,
          "사례 "+(ci+1)+"/"+CASES.length, lang),
        h('span',{style:{margin:"0 6px",color:muted}},"›"),
        h('strong',{style:{fontWeight:700}},
          T("Rubric "+(ri+1)+" of "+curCase.rubrics.length,
            "기준표 "+(ri+1)+"/"+curCase.rubrics.length, lang)))
    : null;

  const SL = ({children}) => h('div',{style:{maxWidth:1140,margin:"0 auto",
    padding:"28px 24px 80px",display:"flex",gap:24,alignItems:"flex-start"}},
    h(VignetteSidebar,{caseData:curCase}), children);

  return h(LangCtx.Provider,{value:lang},
    h('div',{style:{background:pageBg,minHeight:"100vh",fontFamily:ffs}},
      h(StickyHeader,{lang,setLang,doneR,totalR,breadcrumb}),
      step==="consent" && h(ConsentScreen,{onAgree:()=>{setStep("instr");scrollTop();}}),
      step==="instr"   && h(InstrScreen,{onStart:()=>{setStep("partA");scrollTop();}}),
      step==="partA" && curRubric && h(SL,null,
        h(PartAScreen,{key:"A-"+curRubric.id,caseData:curCase,rubric:curRubric,
          ci,ri,onNext:goPartB,onBack:goBack,
          draftAnswers:partADraft[curRubric.id]||{},
          onDraftChange:(id,val,cmts)=>setPartADraft(d=>({...d,[curRubric.id]:{answers:{...((d[curRubric.id]||{}).answers||{}), [id]:val}, comments:{...((d[curRubric.id]||{}).comments||{}), ...cmts}}}))})),
      step==="partB" && curRubric && h(SL,null,
        h(PartBScreen,{key:"B-"+curRubric.id,caseData:curCase,rubric:curRubric,
          ci,ri,isLast:doneR+1>=totalR,onSubmit:submitRubric,partAData,onBack:()=>{setStep("partA");scrollTop();},
          bDraft:partBDraft[curRubric.id]||null,
          onBDraftChange:(d1,d2,cmt)=>setPartBDraft(d=>({...d,[curRubric.id]:{d1Order:d1,d2Order:d2,finalCmt:cmt}}))})),
      step==="done" && h(DoneScreen,{responses,onBack:()=>{setStep("partB");scrollTop();}})
    )
  );
}
